# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

create_mr_count_table <- function(df, countValue) {
    .Call(`_mutab_create_mr_count_table`, df, countValue)
}

